#
# Inventory Profiles Next
#
#   Copyright (c) 2024 Plamen K. Kosseff <p.kosseff@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Project information
ipnext.description=Inventory under your control. Sort. Move matching Items. Throw all. Locked slots. Gear sets! And much more.
ipnext.scm=https://github.com/blackd/Inventory-Profiles
ipnext.tracker=https://discord.com/invite/23YCxmveUM
ipnext.docs=https://inventory-profiles-next.github.io/
ipnext.license=AGPL-3
ipnext.contributors="Special thanks to 'Selah (AspieGamer13)'"
ipnext.contributors.forge=Special thanks to:\
  'Selah (AspieGamer13)'

# Gradle stuff
org.gradle.jvmargs=-Xmx4096M
org.gradle.vfs.watch=true
kapt.use.worker.api=true
#kapt.include.compile.classpath=true
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.warning.mode=all
#org.gradle.logging.level=info

org.gradle.daemon=true
