# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="kotlinforforge"
loaderVersion="[5.3,)" # Require at least 5

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/blackd/Inventory-Profiles/issues" #optional

license="@LICENSE@"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="mixins.ipnext.json"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="inventoryprofilesnext" #mandatory
version="@VERSION@" #mandatory
displayName="Inventory Profiles Next" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next" #optional
logoFile="icon_8.png" #optional
credits='''

This release was made possible by:
  WeConnected

Special thanks ot:
  Selah (AspieGamer13)

'''
authors='''blackd/mirinimi''' #optional
description='''
Take controll over you inventory
'''

[[dependencies.inventoryprofilesnext]] #optional
modId="neoforge" #mandatory
mandatory=true #mandatory
versionRange="[20.0.147,)" #mandatory
ordering="NONE"
side="CLIENT"

[[dependencies.inventoryprofilesnext]]
modId="minecraft"
mandatory=true
versionRange="[1.21,)"
ordering="NONE"
side="CLIENT"

[[dependencies.inventoryprofilesnext]]
modId="libipn"
mandatory=true
versionRange="[@LIBIPN_VERSION@,6.1)"
ordering="NONE"
side="CLIENT"
